name: LyttleEssentials
version: '${projectVersion}'
main: com.lyttledev.LyttleEssentials
api-version: '1.20.6'
authors:
  - Stualyttle
  - ThatsATim

dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
      join-classpath: true