name: LyttleEssentials
version: '${projectVersion}'
main: com.lyttledev.lyttleessentials.LyttleEssentials
api-version: '1.20.4'
authors:
    - Stualyttle
    - ThatsATim
description: Lightweight Essentials plugin.
depend:
  - Vault

commands:
  atp:
    description: teleport for staff free of charge!
    permission: fly_activate_other_sender

  tp:
    description: Allows players to teleport using their tokens.
    permission: lyttleessentials.tp.others

  tpaccept:
    description: Accept incoming requests

  tpdeny:
    description: Deny incoming requests

  lyttleessentials:
    description: Admin command, mainly reload the config without the rest of the server
    permission: lyttleessentials.lyttleessentials

  spawn:
    description: Teleport to spawn

  setspawn:
    description: Set spawn
    permission: lyttleessentials.spawn.set

  delspawn:
    description: Delete spawn

  home:
    description: Teleport to a home

  sethome:
    description: Set a home
    permission: lyttleessentials.home.set

  delhome:
    description: Delete a home

  warp:
    description: Teleport to a warp

  setwarp:
    description: Set a warp

  delwarp:
    description: Delete a warp

  fly:
    description: Toggle fly
    permission: lyttleessentials.fly

  heal:
    description: Heal someone
    permission: lyttleessentials.heal