name: Release & Publish Packages (Alpha Branch)

on:
  push:
    branches:
      - alpha

jobs:
  publish:
    # Only run this workflow for pushes to the default repository
    if: github.repository_owner == 'Lyttle-Development'
    runs-on: ubuntu-22.04
    env:
      GPR_USER: ${{ secrets.GPR_USER }}        # GitHub Packages username
      GPR_API_KEY: ${{ secrets.GPR_API_KEY }}  # GitHub Packages token
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        # Checks out your code so the workflow can access it

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
        # Ensures the checked-in Gradle wrapper is valid and secure

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
          check-latest: true
        # Sets up Java 21 for building and publishing

      - name: Publish to GitHub Packages (Maven)
        env:
          USERNAME: ${{ secrets.GPR_USER }}  # GitHub Packages username
          TOKEN: ${{ secrets.GPR_API_KEY }}  # GitHub Packages token
          CHANNEL: 'Alpha'                   # Github Release channel
        run: |
          # Publishes artifacts to GitHub Packages (Maven)
          ./gradlew publish --stacktrace

      - name: Publish to Hangar (Upload)
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}  # Hangar API token (secret)
          CHANNEL: 'Alpha'                                   # Hangar release channel
        run: |
          # Uploads the plugin to Hangar platform
          ./gradlew publishPluginPublicationToHangar --stacktrace

      - name: Publish to Modrinth (Upload)
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}  # Modrinth API token (secret)
          CHANNEL: 'Alpha'                               # Modrinth release channel
        run: |
          # Publishes to Modrinth (ensure your build.gradle is configured for this)
          ./gradlew modrinth --stacktrace
        # If your Modrinth Gradle task is named differently, update this accordingly