name: BETA Workflow

on:
  push:
    branches:
      - beta

jobs:
  publish:
    # Makes sure the task only runs on pushes to your repository and doesn't fail on forks.
    if: github.repository_owner == 'Lyttle-Development'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          check-latest: true
      - name: Publish
        env:
          HANGAR_API_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
          CHANNEL: 'Snapshot'
        run: ./gradlew build publishPluginPublicationToHangar --stacktrace