name: MAIN Workflow

on:
  push:
    branches:
      - main

jobs:
  publish:
    # Makes sure the task only runs on pushes to your repository and doesn't fail on forks.
    if: github.repository_owner == 'Lyttle-Development'
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - name: Publish
        env:
          HANGAR_TOKEN: ${{ secrets.HANGAR_API_TOKEN }}
          CHANNEL: 'Release'
        run: ./gradlew build publishPluginPublicationToHangar --stacktrace